version: '3'

services:
  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: snitram13/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: snitram13/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "5555:80"  

networks:
  laranet:
    driver: bridge 